name: Upload Audio Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Upload Audio File
        run: |
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
          gh repo clone happymod-audio
          cp C:\Users\KBSS\Downloads\HappyModBetter\src\main\resources\test_audio.wav
          cd happymod-audio
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add new audio file"
          git push
