name: Update Audio File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli@v3

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Update audio file
        run: |
          echo "Updating audio file" > audiofile.txt
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update audio file"
          git push
